### PR TITLE
Performed EDA: Handled Missing Values and Outliers in Stock Price Data

### PR DESCRIPTION
**Pull request by RB137**
I have handled the data quality issues in the stock price dataset and fixed the problems related to missing values and outliers mentioned in issue #137 :

Fixes: #137

Handling Missing Values:

Used forward fill (ffill) to fill missing values in the Open, High, Low, Close, Adj Close, and Volume columns, ensuring data continuity for time-series analysis.

Outlier Treatment:

Applied the Interquartile Range (IQR) method to detect and cap outliers in the stock price columns, preventing distortion from extreme values and creating a more reliable dataset.
These fixes enhance the dataset's quality, making it ready for further analysis and predictive modeling. 

Before:

Screenshot 2024-10-20 015427

After:

image
image

Added documentation to enhance code readability : 

image
image

### CODE REVIEW

**Comment by RB137** [comment]
I’ve handled missing values and outliers and added some documentation. 
Have a look at it, review it, and kindly accept my PR! @rohitinu6

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Comment by RB137** [comment]
@Mayureshd-18 Thanks for the approval! Please add the gssoc-ext, hacktoberfest, hacktoberfest-accepted, and suitable level labels, and kindly merge it to close the issue. @rohitinu6

**Review by rohitinu6 — APPROVED** [review]

**Comment by RB137** [comment]
@rohitinu6 @Mayureshd-18 
Thanks for approving. The issue seems fixed, so please merge my PR and close the issue.

**Comment by RB137** [comment]
@rohitinu6 @Mayureshd-18 
Also, please label it as level 2, as it matches the difficulty level of data refinement.  and outliers handling

**Comment by Mayureshd-18** [comment]
@RB137 The assigned level 1 is appropriate based on the root objective which is the refinement of code. Higher levels are reserved for new algos and procedures.
Thanks for understanding! Merging!

**Pull request merged**
