### PR TITLE
building a website for stock price prediction

### PR DESCRIPTION
**Pull request by spandana2004**
Developed a Streamlit web app that showcases the existing stock price prediction model. The app will allow users to input relevant stock features, view predicted prices, and visualize historical stock data. This will enhance user experience and make the model more accessible. Streamlit's interactive widgets and layout options will be utilized to create an intuitive interface for users.
fix: #125 
image
image

### CODE REVIEW

**Review by jvedsaqib — APPROVED** [review]
Checked it
Thanks for the contribution @spandana2004

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by rohitinu6 — CHANGES_REQUESTED** [review]
image

**Please sync fork with the latest changes**

**Comment by rohitinu6** [comment]
@spandana2004 if you can pls sync it again

**Comment by spandana2004** [comment]
I have synced

**Comment by spandana2004** [comment]
@rohitinu6 can u pls check if the sync is proper n merge the request. Thank u

**Review by Mayureshd-18 — COMMENTED** [review]
Closing this PR due to long period of inactivity. please feel free to reopen if needed.

Regards,
Mayuresh

**Pull request closed without merging**
