### PR TITLE
Update code-of-conduct.md

### PR DESCRIPTION
**Pull request by Nikhil0-3**
fixes issue #143 
As per the issue #143
I have made all the required changes in following topics-
I want to add following points-
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion
Also , I tried to make it more creative.
If any further changes required please tell me.

Fixes issue #143

Screenshot 2024-10-23 082426

Screenshot 2024-10-23 082438
Screenshot 2024-10-23 082448

### CODE REVIEW

**Review by rohitinu6 — APPROVED** [review]

**Comment by rohitinu6** [comment]
@Nikhil0-3 please edit the main comment and mention the issue number resolved using #

**Comment by Nikhil0-3** [comment]
> @Nikhil0-3 please edit the main comment and mention the issue number resolved using #

My issue no. #143

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@Nikhil0-3  Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Please refer to other PRs where the issues are linked to PRs. It should be visible on the Pull Requests page.

Thanks & regards.

**Comment by Nikhil0-3** [comment]
As per the issue #143 I do the following changes
I added the following points-
Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines (Correction, Warning, Temporary Ban, Permanent Ban)
Attribution

Also I tried to make it more creative.
If any further changes required please tell me.

**Comment by Nikhil0-3** [comment]
Please verify it and if any other changes required please let me know.

**Comment by Nikhil0-3** [comment]
Please add the lebels of 
Hacktoberfest 
Gssoc24 extd
And level 2

It will be a great help from your side

**Comment by Nikhil0-3** [comment]
Please merge it.

**Comment by Nikhil0-3** [comment]
Please merge it to your repository

**Comment by Nikhil0-3** [comment]
Please merge it to your repository

**Comment by Mayureshd-18** [comment]
@Nikhil0-3 Please link the issue correctly to the PR as mentioned in my requested changes.

**Comment by Nikhil0-3** [comment]
I already linked the issue 
My issue No.is #143

**Comment by Nikhil0-3** [comment]
Please merge it into your repository

**Review by Mayureshd-18 — COMMENTED** [review]
Closing this PR due to inactivity! Please feel free to reopen in case needed

**Pull request closed without merging**
