### PR TITLE
requirements.txt

### LINKED ISSUE #95: requirements.txt missing
@rohitinu6 please assign someone to add requirements.txt 
Thank you

### PR DESCRIPTION
**Pull request by Pankaj4152**
closes #95 issue, added the requirements.txt file

### CODE REVIEW

**Comment by Mayureshd-18** [comment]
@Pankaj4152 Please link the issue using appropriate actions (fixes/closes). (In this case, closes).

Thanks & Regards.

**Comment by Pankaj4152** [comment]
Why is it failing I don't get it, can you help me with this?

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me. @rohitinu6 Please verify the technical details once.

Thanks

**Review by jvedsaqib — APPROVED** [review]
@rohitinu6 
You can check and merge it

Thanks

**Comment by Mayureshd-18** [comment]
@Pankaj4152 Please resolve the conflicts

**Comment by Pankaj4152** [comment]
i think that as the requirement.txt file don't have the write access so its conflicting the file so can you give it write access them once and then check it again?
@rohitinu6

**Review by jvedsaqib — APPROVED** [review]
Checked the file
as there are some packages that are somewhat large in size 
while rest are small so its good overall

**Pull request merged**
