### PR TITLE
Created a Web Page for predicting the stock price and also implemented concept of ensemble learning closes #132

### LINKED ISSUE #132: Web Page for this predictor using flask
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This is request that I want to add a web page so that it is easy for user to predict by inputting features on webpage and not python interface directly

### Proposed Solution

I want to add a webpage using flask , html and css

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I have experience in creating this kind of websites and want to contribute you can check my github as well

### PR DESCRIPTION
**Pull request by balbirs22**
### Issue Reference:
Closes #132

### Description of changes: Closes #132 
- I have created a web page for predicting stock prices using ensemble learning techniques.
- The page allows users to input stock data and get predictions.
- Ensemble learning models like Random Forest and Gradient Boosting have been implemented to improve prediction accuracy.
- Additional features include data visualization and performance metrics to help users understand the predictions.

stock_price_home
stock_price_predict

### CODE REVIEW

**Comment by balbirs22** [comment]
I have checked and I have done all the tasks

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@balbirs22 Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by balbirs22** [comment]
How I have done please review

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by rohitinu6 — APPROVED** [review]

**Comment by rohitinu6** [comment]
please sync your repo with the latest changes

**Comment by rohitinu6** [comment]
@balbirs22  you will also need to mention the steps in contributing.md

**Comment by jvedsaqib** [comment]
@balbirs22 please ensure that all other notebooks in the main repo that you are not working is present in your commit

**Comment by balbirs22** [comment]
@jvedsaqib I have ensured that as I only added or modified notebooks and not deleted any thing

**Review by jvedsaqib — APPROVED** [review]

**Pull request merged**
