### PR TITLE
Update Overview Section and Fix Image Visibility in Performance Metrics [Fixed #196]

### LINKED ISSUE #196: Update Overview Section and Fix Image Visibility in Performance Metrics
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description
This issue includes two parts:

1. **Update the Overview Section**: The current "Overview" section lacks detailed information. Updating it would help provide better context about the project’s purpose, data source, and objectives, which is essential for new users to understand the project.

   Suggested update for the overview:
   ```markdown
   ## 🌞 Overview
   This project aims to predict the stock prices of **The State Bank of India (SBI)** using various machine learning regression algorithms. By leveraging historical stock data sourced from Yahoo Finance, this project provides insights into the performance of different regression models in stock price prediction for SBI.

   The primary objective is to compare model accuracy and performance metrics, such as RMSE, MAE, and MAPE, across multiple algorithms, ultimately identifying the most suitable regression approach for stock price forecasting.
   ```

2. **Fix Image Visibility in Performance Metrics**: In the "Performance Metrics" section, the images intended to show the Root Mean Square Error (RMSE), Mean Absolute Error (MAE), and Mean Absolute Percentage Error (MAPE) for different regression algorithms are not loading. They appear as broken image icons. Correcting the image paths or links would improve the document's readability and presentation.

### Steps to Reproduce
1. Go to the **Performance Metrics** section of the document.
2. Check the images intended to display RMSE, MAE, and MAPE values for 10 regression algorithms.
3. Observe that the images are not visible and appear as broken icons.
4. Review the **Overview** section for clarity and detail.

### Screenshots
Please see the attached screenshots for reference:

1. **Performance Metrics with broken image icons**: 
Screenshot 2024-10-27 133707

3. **Current Overview Section**: 
Screenshot 2024-10-27 133857

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this.

To address this issue, I would:
- Update the "Overview" section by editing the README or relevant markdown file to include the suggested content.
Screenshot 2024-10-27 134912

- Check the file paths or links for images in the "Performance Metrics" section to ensure correct display, possibly by confirming the images are correctly referenced and available in the repository.
Screenshot 2024-10-27 134927
Screenshot 2024-10-27 134944
Screenshot 2024-10-27 134952
---

### PR DESCRIPTION
**Pull request by Karthik3904**
closes #196 

### Description
This pull request addresses two improvements:

1. **Updated the Overview Section**: Enhanced the "Overview" section to provide more clarity about the project's purpose, data source, and objectives. This update makes it easier for users to understand the goal and scope of the project. The new content includes a detailed explanation of the project’s focus on predicting stock prices for the State Bank of India (SBI) using machine learning regression algorithms.

2. **Fixed Image Visibility in Performance Metrics**: Corrected the broken image links in the "Performance Metrics" section. The images for Root Mean Square Error (RMSE), Mean Absolute Error (MAE), and Mean Absolute Percentage Error (MAPE) are now visible, displaying the performance metrics for the 10 regression algorithms.

This PR enhances the readability and presentation of the documentation, providing a better user experience. 

Screenshots of the changes have been included
Screenshot 2024-10-27 134912
Screenshot 2024-10-27 134927
Screenshot 2024-10-27 134944
Screenshot 2024-10-27 134952

### CODE REVIEW

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@Karthik3904
1. Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2. Please reduce the size of images.

**Comment by Karthik3904** [comment]
I made the following changes. Please accept my PR and merge it. Thank you for your valuable time

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by rohitinu6 — CHANGES_REQUESTED** [review]
@Karthik3904 I believe you are not using the updated version of this repo in your code:
image

That is also the reason why the very first image in the readme file, which is the screenshot of the webpage does not match with the latest version of the repo

**I would suggest you to sync fork and make all the updates**

**Comment by Karthik3904** [comment]
I Synced and updated my repo

Screenshot 2024-10-30 083603

**Review by rohitinu6 — APPROVED** [review]

**Comment by Karthik3904** [comment]
Thank You. Happy Diwali🎉💥

**Pull request merged**
