### PR TITLE
Combined file

### PR DESCRIPTION
**Pull request by Pankaj4152**
I have combined all the files present in the Repository. I tried not to make any mistakes, but if it still have, please tell me. and any suggestions also.

Issue #80 

@rohitinu6 or @jvedsaqib can you plz check the file and merge it?

### CODE REVIEW

**Comment by jvedsaqib** [comment]
Hi @Pankaj4152 can you share a screenshot of how the file structure looks.
You can put all the notebooks in a redundant folder for references and only have the merged notebook out at the front

**Comment by jvedsaqib** [comment]
@Pankaj4152 can you change it like this?


image

**Comment by Pankaj4152** [comment]
> @Pankaj4152 can you change it like this?
> 
> image

sure

**Comment by Pankaj4152** [comment]
> Hi @Pankaj4152 can you share a screenshot of how the file structure looks. You can put all the notebooks in a redundant folder for references and only have the merged notebook out at the front

image

**Comment by jvedsaqib** [comment]
Ok @Pankaj4152 
Thanks for the contribution
and raise the issue for the file structure changes

**Pull request merged**
