### PR TITLE
Modified LSTM Model (2 - Layers) with Dropout Layer to Improve Sequence Processing

### LINKED ISSUE #91: Enhance LSTM Model with Multiple LSTM and Dense Layers
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, the current implementation of the LSTM model is limited to a single layer, which may not fully capture the complexity of long-term dependencies and temporal patterns in sequential data. This limitation can result in suboptimal performance for tasks that require deeper learning capabilities. Adding multiple LSTM layers and dense layers aims to overcome this limitation, enhancing the model’s ability to generalize and produce more accurate predictions.

### Proposed Solution

I propose enhancing the existing LSTM model by stacking 2-3 LSTM layers to capture both short-term and long-term dependencies in sequential data. Dense layers will be added after the LSTM stack for better feature extraction, and dropout regularization will be applied to prevent overfitting. Additionally, we will tune hyperparameters such as LSTM units, dropout rates, and layer configurations to optimize performance.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will modify the existing LSTM model using TensorFlow/Keras by stacking multiple LSTM layers and adding Dense layers for better feature extraction. The implementation will also include dropout regularization to prevent overfitting.

Please assign me this issue .
@rohitinu6

### PR DESCRIPTION
**Pull request by deepanshubaghel**
I have added 2 - layer LSTM model (model10) to enhance sequence processing in the project. The model includes the following layers:

LSTM Layer with 300 units and return_sequences=True.
Dropout Layer with a rate of 0.4 to prevent overfitting.
Second LSTM Layer with 160 units and return_sequences=False for final sequence output.
Dense Layer with 50 units.
Final Dense Layer with 1 unit for output.

closes #91 

@rohitinu6 or @jvedsaqib can you plz check the file and merge it?

### CODE REVIEW

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me. @rohitinu6 Please check for the technical details ones.

**Comment by deepanshubaghel** [comment]
@jvedsaqib @rohitinu6  please review it

**Comment by deepanshubaghel** [comment]
@rohitinu6  is there any issue i didnt get it

**Review by jvedsaqib — COMMENTED** [review]
@deepanshubaghel 
You are deleting the notebook and creating a new notebook
Does it contain all necessary code?

**Comment by deepanshubaghel** [comment]
@jvedsaqib @rohitinu6 please review it

**Review by Mayureshd-18 — APPROVED** [review]

**Pull request closed without merging**
