### PR TITLE
Removal of Classification Metrics

### LINKED ISSUE #35: Removal of Classification Metrics from Regression Model Evaluation
I’ve also noticed that the evaluation of the regression model includes classification metrics such as accuracy, precision, recall, F1 score, and confusion matrix. These metrics are specifically designed for classification tasks where the goal is to predict discrete labels. However, in project which involves Stock Price Prediction which is a regression tasks, the objective is to predict continuous values, making these metrics irrelevant and potentially misleading when evaluating model performance.

Since metrics like Mean Absolute Error (MAE), Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and Mean Absolute Percentage Error (MAPE) are already implemented and are appropriate for this regression task, I suggest removing the classification metrics. This will help maintain clarity and focus on relevant performance indicators.

### PR DESCRIPTION
**Pull request by AnujSaha0111**
Closes #35 

updating Regression metrics
In project which involves Stock Price Prediction which is a regression tasks, the objective is to predict continuous values, making these metrics irrelevant and potentially misleading when evaluating model performance.

Since metrics like Mean Absolute Error (MAE), Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and Mean Absolute Percentage Error (MAPE) are already implemented and are appropriate for this regression task, I suggest removing the classification metrics. This will help maintain clarity and focus on relevant performance indicators.

### CODE REVIEW

**Comment by AnujSaha0111** [comment]
Following https://github.com/rohitinu6/Stock-Price-Prediction/issues/35 is solved

**Comment by jvedsaqib** [comment]
@AnujSaha0111 please resolve the conflict

**Comment by AnujSaha0111** [comment]
facing issues in resolving the conflicts

**Review by jvedsaqib — CHANGES_REQUESTED** [review]
Please synchronize the project first, then proceed to make the necessary changes. Once the code has been updated, kindly commit the changes and submit a pull request.

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@AnujSaha0111 Its been a long time since you have created this PR. Please update, resolve and make the requested changes as soon as possible.

Thanks and regards

**Review by Mayureshd-18 — COMMENTED** [review]
Closing this PR for long period of inactivity. Feel free to reopen!

Thanks,
Mayuresh

**Pull request closed without merging**
