### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sakshamsaraf23**
Added the list of contributors in the Readme.md file
this solves #46 
here is a glimpse:
Screenshot 2024-10-05 204155

### CODE REVIEW

**Comment by rohitinu6** [comment]
@sakshamsaraf23 great, ensure you star the repo, your work will be soon reviewed by the mentors

**Comment by sakshamsaraf23** [comment]
sure sir

**Comment by rohitinu6** [comment]
@sakshamsaraf23 , name of all the contributors is not visible, please look into it

**Comment by sakshamsaraf23** [comment]
sir i only have to put some code and then github does all the things automatically and it's also dynamic so if it missed some people it will be updated in soon

**Pull request merged**
