### PR TITLE
Implement GitHub PR Issue Checker Workflow

### LINKED ISSUE #146: Implement PR Issue Checker Workflow
**Description:** We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

**PR Description Check:** Every PR must have a description. If the description is missing, the PR should fail the check.
    
**Issue Reference Check:** The PR description must include an issue reference in the format Fixes #<issue-number>. If the PR is not addressing an existing issue, it should mention Fixes #NEW as a placeholder.

**Acceptance Criteria:**

- A GitHub Action workflow is triggered on PR events (opened, edited).

**The workflow checks the PR body for:**
- A non-empty description.
- The presence of Fixes #<issue-number> or Fixes #NEW.

**If the criteria are not met:**

- The workflow should fail and return clear error messages.

**If the checks pass:**
- A confirmation message is outputted.

**Expected Output:**

- Error message if the PR description is missing.
- Error message if the issue reference is missing or incorrectly formatted.
- Success message when all checks are satisfied.

**Additional Notes:**

- This issue may serve as a foundation for more advanced PR validation (e.g., commit message format, label enforcement).
- We can later extend this to check for specific branch naming conventions or enforce the addition of specific labels.

_**Note**_: i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!

@rohitinu6

### PR DESCRIPTION
**Pull request by smog-root**
Closes #146 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes , Close, Closes, Closed , Fix , Fixed , Resolve , Resolves #Issue_number`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@rohitinu6

### CODE REVIEW

**Review by rohitinu6 — APPROVED** [review]

**Comment by smog-root** [comment]
Add labels!! And assign me!

**Comment by rohitinu6** [comment]
@smog-root mentors will review and merge the PR

**Comment by smog-root** [comment]
> @smog-root mentors will review and merge the PR

You can add the labels right??

**Comment by Mayureshd-18** [comment]
@smog-root Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards.

**Comment by Mayureshd-18** [comment]
> > @smog-root mentors will review and merge the PR
> 
> You can add the labels right??

I will add the labels after my review.

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@smog-root  Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by smog-root** [comment]
@Mayureshd-18 changes done! ✅

**Comment by smog-root** [comment]
You can review now I added close

closes

closed

fix

fixes

fixed

resolve

resolves

resolved

**Comment by Mayureshd-18** [comment]
@smog-root Don't change the workflow jobs. I meant to change the PR description to link the issue by using keywords. (fixes/closes). Please check other PRs that are merged for reference.

**Comment by smog-root** [comment]
@Mayureshd-18 is it okay now!??

**Comment by jvedsaqib** [comment]
> @Mayureshd-18 is it okay now!??

@smog-root  Edit your first comment. 
The word 'closes' is styled as **\\closes\**. 
Remove the asterisks.

**Comment by smog-root** [comment]
@jvedsaqib done 👍

**Comment by smog-root** [comment]
@Mayureshd-18 it's level2 on issue!

**Comment by smog-root** [comment]
don't decrease the level!

**Review by rohitinu6 — APPROVED** [review]

**Comment by smog-root** [comment]
Add level2 label @rohitinu6

**Review by MastanSayyad — COMMENTED** [review]
workflows = level 1

**Comment by smog-root** [comment]
@MastanSayyad why you removed level label?? Add level1!!

**Pull request merged**
