### PR TITLE
Added SMA and EMA calculations

### LINKED ISSUE #16: Incorporate feature engineering for enhanced model performance
Hello ! @rohitinu6 

I can add another layer of feature engineering where derived features are created from the existing data. 
I am suggesting technical indicators like SMA or EMA. Since the algorithms use random forest and LSTM, it would work well. 

Currently, I am learning about these and implementing these would help!

Can you please assign me this?

Contributor (GSSoc extended)

### PR DESCRIPTION
**Pull request by AnsharaFayazBeigh**
Closes #16 
Issue Reference: #16 

I have put the updated file where I have put the SMA and EMA calculations!
Added SMA and EMA calculations to the stock price prediction model
Implemented calculations for Simple moving average and exponential moving average to improve the model's predictive abilities..

### CODE REVIEW

**Comment by AnsharaFayazBeigh** [comment]
The issue was #16 
@rohitinu6 
Please guide me what is the next step

**Comment by jvedsaqib** [comment]
@AnsharaFayazBeigh you created a new notebook?

**Comment by AnsharaFayazBeigh** [comment]
Yes I did! @jvedsaqib

**Comment by AnsharaFayazBeigh** [comment]
@rohitinu6 Please review It!

**Comment by jvedsaqib** [comment]
@AnsharaFayazBeigh can you do the changes on the actual notebook itself?
As new NB would create confusion.

Please star the repo if you haven't

**Comment by AnsharaFayazBeigh** [comment]
@jvedsaqib Thanks for the feedback! I’ve been using Google Colab for the notebook, and I ended up having to create a new one to make everything work. Because of that, I can’t update the original notebook directly. Do you have any suggestions on how I can merge my changes, or what I should do next? I’d really appreciate any help! Thanks so much!

I did star the repo!

**Review by jvedsaqib — APPROVED** [review]

**Comment by AnsharaFayazBeigh** [comment]
This PR addresses the issue #16 
Can you also assign the labels to this PR ( hacktoberfest-accepted, gssoc-ext)?

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@AnsharaFayazBeigh Please sync your branch with the latest changes. There maybe chances of conflict which are not reflecting now. After sync if there are no conflicts will merge the PR.

Thanks

**Pull request closed without merging**
