### PR TITLE
Added Eda to Market Trend Classification Model #206

### LINKED ISSUE #202: [FEATURE] <Adding Eda to Market Trend Classification Model>
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As i have noticed that while in classification there are some parts needs to be implement which is essential for project like eda , data pre processing concept are not there in Market Trend Classification Model .
@rohitinu6  if liked my approach pls assign me this issue so that i will implement above concepts

### Proposed Solution

Better visualization , cleaned data , better user experiance.

### Screenshots

@rohitinu6 once you will assign this i will work on it !

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will implement using code of python. I will used different liabraries like numpy , matplotlib , seaborn ..!

### PR DESCRIPTION
**Pull request by SimranShaikh20**
fixes - #202 
Issue no - #202 
Closes #202

I have added eda to market trend classification !

@rohitinu6 pls review it and if there is any conflicts let me know !

### CODE REVIEW

**Comment by SimranShaikh20** [comment]
@rohitinu6 
@Mayureshd-18 
@jvedsaqib

**Review by rohitinu6 — APPROVED** [review]

**Comment by SimranShaikh20** [comment]
@jvedsaqib kindly review PR !

**Comment by SimranShaikh20** [comment]
> Looks good to me!

then pls merged PR

**Comment by SimranShaikh20** [comment]
@Mayureshd-18 
@rohitinu6 @jvedsaqib 
pls merged my PR as today is last day for this event

**Pull request closed without merging**
