### PR TITLE
Enhance README by Adding GitHub Repository Statistics Section and Project Title GIF [Fixed #173]

### LINKED ISSUE #168: Update Readme
As now there is a webpage for the project
So the image at the top of the readme can be changed and also steps are needed on how to run the webpage using flask.

@rohitinu6 you can assign someone at FCFS

Thank you

### LINKED ISSUE #173: Add GIF-Based Title to README.md for Enhanced Visual Appeal
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current `README.md` does not have a visually engaging title, and it may not immediately capture the attention of new users or contributors. Adding a GIF-based title would enhance the visual appeal and make the repository stand out, especially during events like Hacktoberfest where numerous repositories compete for attention.

#### **Proposed Solution:**
I propose to include a GIF-based title at the top of the `README.md`. The GIF would represent the project or its theme in a creative and dynamic way, while still maintaining a professional appearance. The GIF should be optimized to prevent slow page load times and should complement the repository's content. 

### Screenshots

Before:
- Current plain text title/header at the top of the `README.md`.
Screenshot 2024-10-23 183236

After:
- A dynamic GIF title at the top to make the repository visually appealing and engaging.

https://github.com/user-attachments/assets/2a4c3259-c8b2-4a2e-ad0c-8ea9ea4f6186

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I would implement the GIF-based title in the following steps:

1. **Create or Choose an Appropriate GIF**:
   - I will either design a simple, looping GIF that reflects the project’s theme, or I will select a relevant GIF from a public source (ensuring no copyright issues).
   - The GIF will be visually appealing but not too large, to prevent slowing down page load times. An ideal size would be around **100-200KB**, optimized for the web.

2. **Add the GIF to `README.md`**:
   - I will edit the `README.md` file and include Markdown syntax to embed the GIF at the top of the file:
 
   - This will ensure the GIF is displayed as a title or banner, introducing the project in a more dynamic way.

3. **Test for Performance**:
   - After adding the GIF, I will test the repository page's load time to ensure the GIF does not negatively impact performance.
   - If the GIF is too large, I will compress it further using tools like **TinyPNG** or **Giphy's compression tools**.

4. **Update README.md**:
   - I will push the updated `README.md` file with the embedded GIF to the repository.
   - I’ll check the final look to ensure it’s properly aligned and the page remains user-friendly and visually appealing.

---

### PR DESCRIPTION
**Pull request by Karthik3904**
closes #173 
closes #168 
### Description:
This pull request includes the following enhancements to the project's README:

1. **Enhanced Project Title with GIF**:
   - A GIF has been added to the project title section for a more dynamic and appealing visual presentation.

https://github.com/user-attachments/assets/0932049b-e973-4244-9d59-846aaffe10db

2. **Added GitHub Repository Statistics**: 
   - A section has been added to display important repository statistics like:
     - ⭐ Stars
     - 🍴 Forks
     - 🐛 Open Issues
     - 🔔 Open PRs
     - 🎯 Closed PRs

   These stats will provide a quick overview of the repository's activity and engagement, making it more informative for potential contributors.

Screenshot 2024-10-24 184000

These improvements aim to make the README more engaging and informative for users and contributors alike.

Please label this PR with:
- gssoc-ext for contributions under GirlScript Summer of Code Extended.
- hacktoberfest-accepted to ensure it counts towards Hacktoberfest.

Thank you for reviewing my contribution! Let me know if any further changes are required.

### CODE REVIEW

**Review by jvedsaqib — CHANGES_REQUESTED** [review]
@Karthik3904 Can you please remove repo stats as it was already done by another contributor

**Comment by Karthik3904** [comment]
Hi [@jvedsaqib  ],

I wanted to apologize for adding the GitHub repository stats without discussing it with you first.  I have removed it in the latest commit.

I appreciate your understanding, and I'll make sure to check in on future changes like this before proceeding. Thank you again for your patience and for considering my pull request!

Best regards,
[@Karthik3904 ]

**Comment by rohitinu6** [comment]
Please make the following changes:
1. As mentioned in issue 168, you need to update the image with the image of the webpage available at main.py.
2. Also add steps to run the main.py file which is a part of issue 168
3. Update the overview section 
4. Images in the performance metrics section is not visible

**Comment by Karthik3904** [comment]
Hi [@rohitinu6]

I have completed the changes requested in issue 168, and I would like to summarize the work done:

Updated the image: I have replaced the existing image with the screenshot of the webpage available in main.py, as requested.
Screenshot 2024-10-25 194943

Added steps to run main.py: Clear instructions to run the Flask application have been added to the README.
Screenshot 2024-10-25 202530


I have already included a GIF format for the title, which enhances the visuals of the project.

However, for the following two changes: 3. Update the overview section 4. Fix the visibility of images in the performance metrics section

I would like to raise these as a separate issue since I am focusing on completing my Hacktoberfest 2024 contributions. This will allow me to address the remaining tasks with proper attention in the next pull request.

Could you kindly accept my current pull request so I can count this towards Hacktoberfest 2024? I will ensure the remaining tasks are completed promptly in the next PR.

Thank you for understanding!

Best regards,
[@Karthik3904 ]

**Comment by rohitinu6** [comment]
@Karthik3904 appreciate your work 
for the overview section, please go through the existing version of readme.md and ensure that it remains same.

**Comment by Karthik3904** [comment]
I made changes in overview section for adding steps executing main.py by using flask app only .
If you want to add any changes please let me know.

**Comment by Karthik3904** [comment]
Dear @rohitinu6  ,

I hope this message finds you well. I kindly request you to review and merge my pull request at your earliest convenience. Additionally, if the contribution meets your standards, please provide the hacktoberfest-accepted label.
Let me know if any further changes are required.

Thank you for your time and consideration.

Best regards,
@Karthik3904

**Review by jvedsaqib — APPROVED** [review]

**Comment by rohitinu6** [comment]
**Existing:**
image

**Your work:**
image

Please make the changes

**Comment by Karthik3904** [comment]
I made the following changes. Thank You for your valuable time

**Review by rohitinu6 — APPROVED** [review]

**Comment by rohitinu6** [comment]
@Karthik3904 , please sync fork with the latest changes so as to merge the pr

**Comment by Karthik3904** [comment]
I've synced my fork with the latest changes. Thank you for accepting my PR!

**Comment by Karthik3904** [comment]
As I mentioned before I rised a separate issue for 
3. Update the overview section 
4. Fix the visibility of images in the performance metrics section
in issue number #196 please assign me in that issue.
Thank You for your valuable time

**Review by Mayureshd-18 — APPROVED** [review]

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@Karthik3904 Assigned you #196 .
Please merge the changes into this same pr.

Thanks and regards

**Comment by Karthik3904** [comment]
Please merge my pull request or it will removed from hacktoberfest for not merging

Screenshot 2024-10-28 143010

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Comment by Karthik3904** [comment]
Please Merge and close this Pull Request and i rised another PR and made the changes @Mayureshd-18 mentioned kindly provide labels merge and close that PR also Thank You for your support

**Pull request merged**
