### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Dipanita45**
Added the security for the website 

Fixes: #212  #209 

Please merge my pull request and label me level2
@rohitinu6

### CODE REVIEW

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@Dipanita45 Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by Mayureshd-18** [comment]
> I have uses fixes keyword @Mayureshd-18

@Dipanita45 Even if you have used it you haven't used it in right manner. Please refer to docs once on how to use it. If still have doubt please let me know!

Thanks

**Comment by Dipanita45** [comment]
Please tell me how to use sir
@Mayureshd-18

**Comment by Mayureshd-18** [comment]
@Dipanita45 It looks like #212 also fixes the same issue. Please close one of the PRs

**Comment by Dipanita45** [comment]
I have closed

**Comment by Dipanita45** [comment]
Please merge #213 and label me level 2

**Comment by Dipanita45** [comment]
Please merge my pull request and label me level 2 
@Mayureshd-18  @rohitinu6

**Comment by Dipanita45** [comment]
Please merge my pull request and label me level 2
@Mayureshd-18 @rohitinu6

**Review by rohitinu6 — CHANGES_REQUESTED** [review]
**@Dipanita45 please sync your fork with the lates updates:**
image

**Comment by Dipanita45** [comment]
i had sync the fork @rohitinu6  @Mayureshd-18

**Comment by rohitinu6** [comment]
@Dipanita45 please do it again

**Comment by Dipanita45** [comment]
Ok, I will do it.

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Comment by Mayureshd-18** [comment]
@Dipanita45 Why are there 2 PRs #212 and #218 ? They both fix the same issues...

**Comment by Dipanita45** [comment]
Please merge #213 and label me level 2

**Comment by Dipanita45** [comment]
Please

**Comment by Dipanita45** [comment]
Please please merge my pull request and label me level 2 
@rohitinu6  @Mayureshd-18 
As tomorrow is last day

**Comment by rohitinu6** [comment]
**@Dipanita45 as I mentioned earlier, you need to sync your fork to get your PR mergerd and you have not done it yet:**
image

Please let me know if you are facing any issue with this

**Pull request closed without merging**
