### PR TITLE
ENHANCE AND STRUCTURE THE CONTRIBUTORS SECTION

### PR DESCRIPTION
**Pull request by alo7lika**
Closes: #158

# Description of changes:
The Contributors section is a vital component of any open-source project, as it acknowledges and celebrates the individuals who have contributed their time and expertise to the development of the software. Recognizing contributors fosters a sense of community and encourages collaboration, which is essential for the project's growth and sustainability. This section serves not only as a record of contributions but also as an inspiration for others to get involved. By highlighting the diverse talents and backgrounds of contributors, it promotes inclusivity and demonstrates the collective effort that drives the project's success. Additionally, a well-structured Contributors section enhances transparency, allowing users to understand who is behind the project and how they can engage with the community. Overall, it is an important tool for building a supportive ecosystem that values collaboration and continuous improvement.
Screenshot 2024-10-24 165218

# Issue Reference:
- Issue #158

### CODE REVIEW

**Comment by alo7lika** [comment]
@rohitinu6  the task has been Completed.

**Comment by rohitinu6** [comment]
@alo7lika will it update the name of future contributors automatically?

**Comment by alo7lika** [comment]
> @alo7lika will it update the name of future contributors automatically?

I appreciate your feedback regarding the hardcoded contributor profiles! While it may seem limiting to use hardcoded profiles, I chose this approach for several reasons. First, it keeps the README structure simple and allows for quick recognition of key contributors, making it easier for users to acknowledge their efforts without the overhead of implementing a dynamic system. Second, hard coding ensures consistency in formatting and presentation, which can sometimes be lost with dynamic solutions. Currently, our project has a small group of core contributors, so manually managing this section allows us to highlight their contributions prominently as we build our community. Lastly, I’m open to revisiting this approach in the future as we grow and welcome more contributors, allowing us to adapt to the project's evolving needs. Thank you for your understanding!

**Comment by rohitinu6** [comment]
@alo7lika please make changes considering the long term pov

**Comment by rohitinu6** [comment]
@alo7lika please sync your repo with the latest changes

**Comment by alo7lika** [comment]
> @alo7lika please sync your repo with the latest changes

done

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by rohitinu6 — APPROVED** [review]

**Pull request merged**
