### PR TITLE
Aarathi contribution - Eliminated Google Drive Mounting and Implemented Logistic Regression

### PR DESCRIPTION
**Pull request by Aarathi1535**
In the code, the datasets are being mounted from google drive which takes more time and lags execution time. Instead the datasets are present in Data directory so fetching from it will be more feasible.
Additional machine learning algorithms i.e Logistic Regression including Ridge, Lasso and Elastnet Regularization were implemented to assess model performance.

A kind request to add (gssoc-ext) and (hacktoberfest-accepted) as labels.

### CODE REVIEW

**Comment by jvedsaqib** [comment]
Hi @Aarathi1535 ,

Thank you for your contribution!
It looks like there is a merge conflict that needs to be resolved before I can merge your PR.

**Comment by Aarathi1535** [comment]
I am not getting the option to resolve conflicts, can you please check it into it and let me know.

**Comment by jvedsaqib** [comment]
@Aarathi1535 
Sync with the latest branch and then change it.
Can you tell me what was the issue number?
Also please star this repo if you haven't
Thank You

**Comment by Aarathi1535** [comment]
The issue number is #42

**Pull request closed without merging**
