### PR TITLE
Added Eda to Market Trend Classification Model

### LINKED ISSUE #202: [FEATURE] <Adding Eda to Market Trend Classification Model>
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As i have noticed that while in classification there are some parts needs to be implement which is essential for project like eda , data pre processing concept are not there in Market Trend Classification Model .
@rohitinu6  if liked my approach pls assign me this issue so that i will implement above concepts

### Proposed Solution

Better visualization , cleaned data , better user experiance.

### Screenshots

@rohitinu6 once you will assign this i will work on it !

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will implement using code of python. I will used different liabraries like numpy , matplotlib , seaborn ..!

### PR DESCRIPTION
**Pull request by SimranShaikh20**
fixes - #202 
Issue no - #202 
Closes #202 

I have added eda to market trend classification  !

@rohitinu6 pls review it and if there is any conflicts let me know !

### CODE REVIEW

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@SimranShaikh20 Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by SimranShaikh20** [comment]
@Mayureshd-18 i have added fixes and close tag
Can you pls and let me know any other changes i have made !

**Comment by SimranShaikh20** [comment]
@rohitinu6 pls check PR and merged it !

**Comment by SimranShaikh20** [comment]
@rohitinu6  can you pls merged this pr?!

**Comment by SimranShaikh20** [comment]
@jvedsaqib  pls check PR and merged it .
If there is any conflicts then let me know!

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@SimranShaikh20 Please use the correct keywords to link the issue. It should be visible on PRs page. Please refer to other merged PRs for reference.

Thanks and regards

**Review by SimranShaikh20 — COMMENTED** [review]
commited

**Comment by SimranShaikh20** [comment]
> @jvedsaqib Checked the code. Lgtm. See on your side pls.

yes pls check i have added

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@SimranShaikh20 As you can see that even after your changes this PR is not linked to the issue correctly as the issue cant be seen on the Prs page directy,
How about you try to add just ```Closes <issueno.>``` in the description directly?

Thanks

**Comment by SimranShaikh20** [comment]
> @SimranShaikh20 As you can see that even after your changes this PR is not linked to the issue correctly as the issue cant be seen on the Prs page directy, How about you try to add just `Closes <issueno.>` in the description directly?
> 
> T

> @SimranShaikh20 As you can see that even after your changes this PR is not linked to the issue correctly as the issue cant be seen on the Prs page directy, How about you try to add just `Closes <issueno.>` in the description directly?
> 
> Thanks

Apologize for inconvenience I had make changes pls check and merged it

**Comment by Mayureshd-18** [comment]
> > @SimranShaikh20 As you can see that even after your changes this PR is not linked to the issue correctly as the issue cant be seen on the Prs page directy, How about you try to add just `Closes <issueno.>` in the description directly?
> > Thanks
> 
> Apologize for inconvenience I had make changes pls check and merged it

@SimranShaikh20 I edited your description. Now as you can see the issue is linked with the PR correctly. Adding the ```"-"``` will changed the format (refer to docs) and the issue was not linked correctly. Keep that in mind and hope you got it!

Thanks

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Comment by Mayureshd-18** [comment]
Will merge immediately after atleast one more review!

Thanks & regards

**Comment by SimranShaikh20** [comment]
> Will merge immediately after atleast one more review!
> 
> Thanks & regards

Okay

**Comment by SimranShaikh20** [comment]
> Looks good to me!

Pls add other label like gssoc ext

**Comment by SimranShaikh20** [comment]
@rohitinu6 pls review to PR and is there any conflicts let me know

**Review by rohitinu6 — CHANGES_REQUESTED** [review]
**Please sync your fork with the latest changes:**
image

**Comment by SimranShaikh20** [comment]
@rohitinu6 apolozies for inconvience update branch and synced repo 
Kindly review my PR and merged it !

**Comment by rohitinu6** [comment]
@SimranShaikh20 it's not done yet

**Comment by SimranShaikh20** [comment]
@rohitinu6  i will make new PR may there is some technical issue from my side

**Pull request closed without merging**
