### PR TITLE
ADDED SOME MORE ALGORITHMS OVERALL 18 ALGORITHMS

### LINKED ISSUE #2: Add more algorithms
Can I add few more algorithms?like lightgbm,catboost,arima etc

### PR DESCRIPTION
**Pull request by piyush182004**
ADDED SOME NEW MORE ALGORITHMS. EACH AND EVERY ALGORTIHMS RMSE,MAE & MAPE plot are done too.
issue number #2    fixes #2

### CODE REVIEW

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@piyush182004 Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by piyush182004** [comment]
yes edited and linked the issue number please check

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by Mayureshd-18 — COMMENTED** [review]
Thank you for your contribution and effort on this PR. As there hasn't been any activity or updates for a while, we will go ahead and close this PR to keep the repository organized. If you’d like to revisit or continue working on this, please feel free to reopen it or submit a new PR.

Thanks again for your work!

Regards,
Mayuresh

**Pull request closed without merging**
