### PR TITLE
Market Trend Classification Model

### PR DESCRIPTION
**Pull request by alo7lika**
Closes: #84

# Description of changes:
The current implementation of the **Market Trend Classification Model** provides a strong framework for identifying and classifying market regimes based on historical stock price data. However, it lacks functionality for:

- **Real-Time Market Adaptation**: The model does not account for dynamic updates based on real-time market conditions, leading to a delay in identifying emerging trends.

- **Incorporation of Alternative Indicators**: The existing model primarily uses historical price data and basic technical indicators. It does not include alternative data sources such as sentiment analysis from news and social media or macroeconomic indicators, which could significantly enhance model accuracy.

- **Visualization and Interpretability**: There is no interactive dashboard or visualization tool for users to easily interpret the model's output. This limitation can hinder understanding and reduce the model's usability for non-technical users.

# Issue Reference:
- Issue #84

### CODE REVIEW

**Comment by alo7lika** [comment]
@rohitinu6 I have completed the task. Please review it.
Thank you!

**Review by jvedsaqib — APPROVED** [review]

**Review by rohitinu6 — APPROVED** [review]

**Comment by alo7lika** [comment]
@Mayureshd-18 kindly review the task

**Comment by alo7lika** [comment]
@Mayureshd-18  kindly review the task

**Comment by alo7lika** [comment]
@rohitinu6  @jvedsaqib Kindly add labels on PR and merge and Close the issue.

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me. Merging!

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@mastansayyad review this PR

**Pull request merged**
