### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Dipanita45**
Added the security of the website 

Fixes : #209 

Please merge the pull request and label me level 2 
@rohitinu6

### CODE REVIEW

**Review by rohitinu6 — APPROVED** [review]

**Review by rohitinu6 — CHANGES_REQUESTED** [review]
@Dipanita45  Please sync your fork with the latest changes:
image

**Comment by Dipanita45** [comment]
Okay I will do as soon as possible

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me other than requested changes!

**Comment by Dipanita45** [comment]
How to refer or uses the keyword 
Sir

**Comment by Mayureshd-18** [comment]
@rohitinu6 After merging it will be auto-fast forwarded. You can proceed with merging.
Thanks

**Pull request closed without merging**
