### PR TITLE
Add StockWise Chatbot Integration for Stock Price Prediction

### LINKED ISSUE #216: Issue: Integrate Chatbot Feature for Stock Price Prediction App
**Objective**:  
Enhance the Stock Price Prediction application by adding a chatbot feature that allows users to interact with the app using a conversational interface. This chatbot will enable users to access stock price predictions, historical data, and general guidance on market trends through an interactive chat format.

**Details**:  
The chatbot should:
- Respond to user inquiries about current stock predictions, historical performance, and market trends.
- Provide insights into key stock performance indicators and factors affecting predictions.
- Assist users with navigating app features and understanding prediction outputs.

**Proposed Solution**:
1. **Conversation Flow Design**: Map out the common types of questions users might ask, such as stock predictions, trend analyses, and help requests. Design response flows for these scenarios to ensure smooth, informative interactions.
2. **Backend Integration**: Connect the chatbot to the existing stock prediction model to provide real-time data in response to user queries. This will ensure that predictions are accurate and up-to-date.
3. **User Interface**: Add a chatbot widget to the main app interface. This should be accessible, engaging, and intuitive, allowing users to start conversations with ease.
4. **Fallback & Context Management**: Implement fallback responses for unrecognized questions and session management to allow the chatbot to handle follow-up questions in a contextual manner.

**Expected Outcome**:  
A fully integrated chatbot that enhances user engagement by providing an interactive way to access stock predictions and market insights, improving overall user experience.

**Request for Assignment**:
Kindly assign this issue to me for contribution under GSSoC-extd

### PR DESCRIPTION
**Pull request by BigBang001**
### Pull Request Description:

This PR integrates the **StockWise** chatbot into the Stock Price Prediction project, enhancing user experience by providing real-time insights, guidance, and stock information.

#### Key Features:

1. **Stock Predictions and Market Insights**  
   - The chatbot provides users with current stock predictions, showing the latest analysis and expected trends.
   - Users can inquire about historical performance to understand how specific stocks have behaved over time.
   - The chatbot also shares market trend information to help users make more informed decisions.

2. **Performance Indicators and Influencing Factors**  
   - **Stock Performance Indicators**: StockWise offers insights into key performance metrics, such as P/E ratios, EPS, market capitalization, and other important indicators.
   - **Factors Affecting Predictions**: The chatbot explains major factors that may impact the stock predictions, like economic news, recent earnings reports, and sector-specific developments.  

3. **User Guidance for App Navigation and Prediction Understanding**  
   - **Navigation Assistance**: Users receive help with navigating app features, making it easier for newcomers to explore stock predictions and data analysis tools.
   - **Prediction Output Explanation**: StockWise assists users in understanding the prediction outputs by breaking down the data and offering explanations of each metric’s significance.

### Screenshots of Integration

**Chatbot Icon on Homepage**  
Screenshot 2024-11-10 131615
131604](https://github.com/user-attachments/assets/3fe415b9-f7c4-4daa-93e0-38126de28d67)

**Chat Interface with Stock Prediction Queries**  
Screenshot 2024-11-10 131604

> **Assigned under**: GSSoC-extd

### CODE REVIEW

**Review by rohitinu6 — CHANGES_REQUESTED** [review]
**@BigBang001 please sync your fork with the latest updates:**
image

**Comment by BigBang001** [comment]
@rohitinu6 I have synced the fork with the latest updates. Now you can check and verify

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@BigBang001 Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by BigBang001** [comment]
@Mayureshd-18 I have linked the PR with the respective issue. Now can check and verify.

**Review by Mayureshd-18 — COMMENTED** [review]
I think the "Id" in stock.html should be mentioned in a .env file instead of directly into the html file.
@rohitinu6 What is your opinion on this?

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by rohitinu6 — APPROVED** [review]

**Pull request merged**
