### PR TITLE
stock-Sentimental issues #145 closes #145

### LINKED ISSUE #145: [FEATURE] <description>Enhancing Stock Prediction Accuracy Using Stock Sentiment Analysis
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Combining stock sentiment analysis with traditional historical data improves stock prediction accuracy by capturing market emotions and reactions. Sentiment analysis uses data from news, social media, and financial reports to gauge market optimism or pessimism. This added layer of information helps models anticipate price movements influenced by market psychology, offering more accurate predictions and better investment insights.

### Proposed Solution

My proposed solution involves using stock market sentiment analysis to assess whether a particular stock will have a positive or negative impact on the market. By analyzing data from news articles, social media, and financial reports, we can gauge the overall sentiment surrounding a stock. This insight allows us to predict how the stock is likely to influence market trends, helping investors make more informed decisions based on the anticipated market response.

### Screenshots

I have previously developed a sentiment analysis model for IMDb movie reviews, and I plan to apply a similar approach to analyze stock market sentiment. By leveraging sentiment analysis techniques, I will assess whether the overall sentiment surrounding a stock is positive or negative, helping to predict how it might impact market movements. This method will provide valuable insights into market trends based on public perception and reactions.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

To technically implement stock market sentiment analysis, I would start by collecting data from various sources such as news articles, social media posts, and financial reports using APIs like Twitter API or web scraping tools. Next, I would preprocess the text data to clean and standardize it, including removing noise like special characters and converting text to lowercase. Using Natural Language Processing (NLP) libraries such as spaCy or Hugging Face Transformers, I would train a sentiment analysis model, or fine-tune a pre-trained model like BERT, to classify each text as positive, negative, or neutral. After assigning sentiment scores to each piece of text, I would aggregate these scores over specific time periods (daily, weekly) and combine them with historical stock price data. Finally, I would use a time-series forecasting model, such as LSTM or Random Forest, incorporating both the sentiment scores and stock data to predict how the stock might influence market trends, providing buy/sell/hold recommendations based on the analysis.

### PR DESCRIPTION
**Pull request by sapnilmodak**
Issue Reference:
Closes #145 

Description of changes:  #145

### CODE REVIEW

**Comment by sapnilmodak** [comment]
closes #145

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@sapnilmodak  Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Comment by sapnilmodak** [comment]
@Mayureshd-18  I have linked issue with closes

**Comment by Mayureshd-18** [comment]
> @Mayureshd-18 I have linked issue with closes

Until the issue is seen on the 'Pull requests' page, its not linked correctly. Please refer to merged PRs for reference.

**Comment by sapnilmodak** [comment]
@Mayureshd-18  is it perfect now?

**Comment by sapnilmodak** [comment]
fixes #145

**Comment by sapnilmodak** [comment]
closes #145

**Comment by sapnilmodak** [comment]
@Mayureshd-18  please check now?

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by jvedsaqib — APPROVED** [review]

**Review by rohitinu6 — APPROVED** [review]

**Comment by sapnilmodak** [comment]
commit the changes @rohitinu6

**Pull request merged**
