### PR TITLE
Added RSI indicator and its graph

### PR DESCRIPTION
**Pull request by Pankaj4152**
Hi @rohitinu6 ,
added the RSI indicator and  its graph, if any improvements possible then please let me know.
Problem- #59

### CODE REVIEW

**Comment by jvedsaqib** [comment]
@Pankaj4152 While you are at it, also add SMA plot for your last PR and commit here.

**Comment by Pankaj4152** [comment]
> Quote reply

how can i commit again don't know. but can raise new issue and commit in that with the SMA graph. If not any problem

**Comment by jvedsaqib** [comment]
> > Quote reply
> 
> how can i commit again don't know. but can raise new issue and commit in that with the SMA graph. If not any problem

@Pankaj4152 Add it with your assigned Issue #60 Ok

**Comment by Pankaj4152** [comment]
can you please add the gssoc-ext and hacktoberfest tags?

**Pull request merged**
