### PR TITLE
Added More Hyperparameters and added VotingRegressor

### PR DESCRIPTION
**Pull request by agnij-dutta**
Fixes [issue #129](https://github.com/rohitinu6/Stock-Price-Prediction/issues/129)

Description of changes:

Added a polynomial feature transformer to create new features for improving model performance.
Introduced a voting regressor that combines multiple model predictions for more accurate results.
Performed hyperparameter tuning for the voting regressor using GridSearchCV, optimizing the weights parameter.
Calculated additional evaluation metrics (accuracy, precision, recall, F1 score, confusion matrix) to provide a comprehensive view of model performance.
Fixed an error by removing the invalid voting parameter in the GridSearchCV call.
Benefits:

Enhanced model accuracy and recall.
More comprehensive evaluation metrics.
Improved hyperparameter tuning process.

### CODE REVIEW

**Comment by jvedsaqib** [comment]
Hey @agnij-dutta please mention the issue #

**Comment by agnij-dutta** [comment]
issue reference [issue #129 ]

**Comment by Mayureshd-18** [comment]
@agnij-dutta Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed please refer to the closed PRs that were merged.

Thanks & regards

**Review by rohitinu6 — APPROVED** [review]

**Comment by rohitinu6** [comment]
@agnij-dutta , kindly edit your main comment, i.e. the first one and mention the issue number in it

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@agnij-dutta Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@agnij-dutta Please quantify your claims. Please add the old vs new accuracy and other evaluation metrics that you have changed.
Maybe you can them in the description of the PR itself. 
Thanks and regards

**Review by Mayureshd-18 — COMMENTED** [review]
@agnij-dutta Closing this PR due to long period of inactivity. Please feel free to reopen if needed.

Thanks,
Mayuresh

**Pull request closed without merging**
