### PR TITLE
Update code-of-conduct.md

### PR DESCRIPTION
**Pull request by Nikhil0-3**
I made all required changes in the code of conduct file.

### CODE REVIEW

**Comment by Nikhil0-3** [comment]
Please assign this to me and accept it

**Comment by rohitinu6** [comment]
@Nikhil0-3 , I appreciate your work, but this is not how you should proceed.
Create an issue first and then a pull request where you mention the issue number,
All the best

**Comment by priyansh985** [comment]
@Nikhil0-3

Use fixes/closes and tag your issue with its #issue-number

Ex:

Closes #issue-number
Fixes #issue-number

Otherwise admin not able to link the issue with correct pull request

Regards
Priyansh985

**Comment by rohitinu6** [comment]
@priyansh985 it will be great if you can make a template for PR in this format to the repo
If you want to work on it, please raise an issue.

**Comment by priyansh985** [comment]
@rohitinu6 sure sir why not

**Pull request closed without merging**
