### PR TITLE
Financial Environment Segmentation

### LINKED ISSUE #79: Financial Environment Segmentation
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Financial Environment Segmentation involves identifying distinct phases in the financial markets, such as bull (rising prices) and bear (declining prices) markets, to aid traders and investors in making informed decisions. The process begins with collecting historical price data and relevant market indicators, followed by feature engineering to calculate daily returns, technical indicators, and volatility measures. Data preprocessing, including normalization and handling missing values, ensures the dataset is ready for analysis. Clustering techniques like K-means, hierarchical clustering, or DBSCAN are then applied to categorize historical price movements into different regimes, with subsequent analysis to label these clusters as bull, bear, or neutral markets based on their characteristics. To predict future market regimes, a regime-switching model or supervised learning methods can be employed. Finally, the model's effectiveness is validated through backtesting against historical data, and visualizations are created to illustrate the identified market phases, ultimately enhancing trading strategies and decision-making based on the current market environment.

### Proposed Solution

The proposed solution for Financial Environment Segmentation involves developing a machine learning model that identifies different market phases, specifically bull and bear markets, using historical stock price data and market indicators. The process begins with collecting comprehensive datasets, including daily stock prices and relevant economic indicators, followed by feature engineering to derive key metrics such as daily returns, technical indicators, and volatility measures. Utilizing clustering techniques like K-means or DBSCAN, the model categorizes historical price movements into distinct regimes. Each identified cluster is then analyzed to determine its characteristics, allowing for the labeling of market conditions as bullish, bearish, or neutral. To enhance predictive capabilities, a regime-switching model or supervised learning algorithms will be implemented, enabling the model to forecast potential transitions between market phases based on current data. The solution will be validated through backtesting against historical performance, ensuring robustness and reliability in real-time applications. Visualizations of market regimes will also be created to aid in the interpretation of results and facilitate informed trading decisions.

### Screenshots

N/A

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

To technically implement the market regime detection solution, the following steps would be undertaken:

Data Collection: Gather historical stock price data using APIs like Alpha Vantage, Yahoo Finance, or Quandl. Include daily open, high, low, close prices, and trading volumes. Supplement this with economic indicators such as interest rates, GDP growth, and volatility indices (e.g., VIX) to provide a comprehensive dataset.

Data Preprocessing: Clean the data by handling missing values through interpolation or forward filling. Normalize the features using techniques like Min-Max scaling or Standardization to ensure they are on the same scale, which is crucial for clustering algorithms.

Feature Engineering: Calculate daily returns and derive technical indicators (e.g., moving averages, RSI, MACD) to capture market trends and momentum. Compute rolling volatility and other relevant features to enrich the dataset for clustering analysis.

Clustering Implementation: Apply clustering techniques, starting with K-means clustering. Use the elbow method to determine the optimal number of clusters (K). Implement K-means using libraries such as Scikit-learn. Additionally, experiment with DBSCAN to identify market regimes without requiring the number of clusters to be predefined.

Cluster Analysis: Analyze the characteristics of each cluster by calculating the average returns and volatility metrics. Label the clusters based on their behavior (e.g., bull, bear, neutral) to facilitate understanding of market regimes.

Predictive Modeling: For regime prediction, implement a regime-switching model using a Markov Chain approach or utilize supervised learning algorithms like logistic regression or random forests. Train the model on features derived from the clustered data to predict future market regimes based on historical patterns.

Backtesting and Validation: Validate the model’s performance through backtesting against historical market data. Assess metrics such as accuracy, precision, recall, and F1 score to evaluate predictive capabilities. Analyze cumulative returns during identified market regimes to demonstrate the model's effectiveness.

Visualization: Create visualizations using libraries like Matplotlib and Seaborn to plot historical price movements, highlighting the identified market regimes. Generate charts displaying cumulative returns for different regimes to illustrate their impact on trading strategies.

Real-Time Integration: Develop a pipeline that allows the model to update continuously with new market data, enabling real-time predictions and insights. Use frameworks like Apache Kafka or Streamlit to facilitate real-time data processing and visualization.

This implementation approach ensures a robust and dynamic system for detecting market regimes, ultimately enhancing trading strategies and decision-making processes.

### PR DESCRIPTION
**Pull request by alo7lika**
Closes #79 

# Description of changes:
- Implemented the Financial Environment Segmentation project to identify and classify different market regimes using historical stock price data.
- Collected data from Yahoo Finance and calculated key financial metrics, including daily returns, moving averages, and volatility.
- Preprocessed and normalized the metrics to create a feature set for analysis.
- Applied K-means clustering techniques to segment the data into distinct market regimes.
- Analyzed each regime for its characteristics and performance, enabling effective backtesting of investment strategies.

# Issue Reference:
- Issue #79

### CODE REVIEW

**Comment by alo7lika** [comment]
@rohitinu6 The task/ Project has been done. You could check it and review it ASAP

**Comment by alo7lika** [comment]
@rohitinu6 The task/ Project has been done. You could check it and review it ASAP

**Comment by Mayureshd-18** [comment]
@alo7lika Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Thanks & regards.

**Comment by alo7lika** [comment]
Fixes rohitinu6/Stock-Price-Prediction #79

**Comment by alo7lika** [comment]
> @alo7lika Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> 
> Thanks & regards.

Fixes rohitinu6/Stock-Price-Prediction #79

**Comment by alo7lika** [comment]
> > @alo7lika Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> > Thanks & regards.
> 
> Fixes rohitinu6/Stock-Price-Prediction #79

@Mayureshd-18 kindly review it. Thank you!

**Comment by Mayureshd-18** [comment]
@alo7lika Please use keywords as they are mentioned in the docs. Then only the issue would be linked to the PR correctly.
If needed please refer to other PRs that have issues linked to them.

Thanks and regards

**Comment by Mayureshd-18** [comment]
Till then @rohitinu6 @jvedsaqib please review the technical details and the file structure. 

Thanks

**Review by jvedsaqib — CHANGES_REQUESTED** [review]
@alo7lika 
Why are you using the image?
Also change the Installation section which should contain how to clone this repo and other necessary things.

**Comment by alo7lika** [comment]
> @alo7lika Please use keywords as they are mentioned in the docs. Then only the issue would be linked to the PR correctly. If needed please refer to other PRs that have issues linked to them.
> 
> Thanks and regards

Fixes rohitinu6/Stock-Price-Prediction #79  is this int how to use the keywords?

**Comment by alo7lika** [comment]
> @alo7lika Why are you using the image? Also change the Installation section which should contain how to clone this repo and other necessary things.

Images have been used to make the project interesting and enhance the look. But will update as you requested

**Comment by jvedsaqib** [comment]
> > @alo7lika Why are you using the image? Also change the Installation section which should contain how to clone this repo and other necessary things.
> 
> Images have been used to make the project interesting and enhance the look. But will update as you requested

@alo7lika 
I suggest you remove them or specify it in other section as the UI like the image is not implemented actually in this notebook

**Comment by alo7lika** [comment]
@jvedsaqib @Mayureshd-18 @rohitinu6 All the changes have been made.
Please review it! 
Thank you!

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Pull request merged**
