### PR TITLE
optimized the code using intel ai analytics toolkit

### LINKED ISSUE #116: [FEATURE] Optimize Stock Price Prediction Code for Intel Hardware Using AI Analytics Toolkit
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes, the current stock price prediction code is not fully optimized for Intel hardware, leading to slower performance, especially with large datasets during data preprocessing and model training. We need to utilize the Intel AI Analytics Toolkit, which offers enhanced parallelism and optimizations through Modin pandas and Intel-optimized scikit-learn. The absence of these optimizations is causing inefficiencies in terms of computation speed and resource utilization.

### Proposed Solution

To optimize the stock price prediction code for Intel hardware, we propose using the Intel AI Analytics Toolkit, which includes Modin for faster data manipulation and Intel-optimized scikit-learn for efficient model training. By replacing standard pandas operations with Modin, the code will leverage parallel processing, speeding up computations on large datasets. Intel-optimized scikit-learn will further accelerate the machine learning workflows by utilizing Intel’s low-level optimizations. Performance improvements will be measured through benchmarks, and profiling tools like Intel VTune can be used to analyze resource utilization. You can also explore Intel's detailed documentation on AI optimizations for more insights.

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

For the implementation, we will first install the necessary libraries from the Intel AI Analytics Toolkit, such as Modin and Intel-optimized scikit-learn. Once installed, we will update the code by replacing the standard pandas with Modin (import modin.pandas as pd), allowing for parallel data processing, which significantly speeds up operations on large datasets. No changes are needed for scikit-learn since the Intel-optimized version will automatically enhance the performance of machine learning models like RandomForestRegressor. After these modifications, we’ll benchmark the performance to ensure the optimizations are effectively improving the computation time.

### PR DESCRIPTION
**Pull request by priyansh985**
Issue #116 
Closes #116 
optimize the stock price prediction code for Intel hardware using oneapi ai analytics toolkit.

This pull request introduces a new branch, intelex, that includes optimizations for the project using the Intel AI Analytics Toolkit. Below are the key updates in this branch:

New Folder: Intel_Optimized

This folder contains the resources optimized for Intel hardware.
Files Added:

requirements.txt: Lists all the necessary dependencies, including Intel-optimized packages.
README.md: Detailed instructions on how to set up the environment, install dependencies, and use the optimized models and data analysis notebooks.
Optimizations:

All primary models and data analysis notebooks in this folder are optimized using:
Intel Distribution of Modin: Enhances pandas performance for faster data manipulation.
Intel Scikit-learn: Accelerates machine learning algorithms for quicker training and inference.

### CODE REVIEW

**Comment by priyansh985** [comment]
hello [ rohitinua6 ] 
i submitted the pull request about the successful implementation of intel ai analytics toolkit specifically intel modin and intel distribution of scikit-learn in this feature implementation i created a new branch called intelex so that the existing pandas and scikit-learn could not cause any errors with intel one's in this new branch i created a new folder called Intel_Optimized int this folder have the necessary files to run the models requirements.txt and readme.md and all notebooks for run and evaluation of the models please kindly review my pull request 

thanks you 
Priyansh jain.

**Comment by jvedsaqib** [comment]
Hi @priyansh985 what was the issue number?
Also can you please use keywords like fixes/closes along with your issue number

**Comment by priyansh985** [comment]
Hello @jvedsaqib
My issue is #116 optimize the code for Intel hardware using Intel OneAPI analytics toolkit..

**Comment by Mayureshd-18** [comment]
@priyansh985 Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed please refer to the closed PRs that were merged.

Thanks & regards

**Comment by priyansh985** [comment]
@jvedsaqib and @Mayureshd-18 
Issue Closes #116 optimize the code for Intel hardware using Intel OneAPI analytics toolkit..

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@priyansh985 Until you see the issue linked to your PR on 'Pull requests' page, it is not linked correctly. Pls refer to other PRs which are linked correctly.

Thanks & regards

**Comment by priyansh985** [comment]
@Mayureshd-18
Ohh thanks mayur I got it I have to mention the issue on my pull request

**Review by rohitinu6 — APPROVED** [review]

**Review by rohitinu6 — APPROVED** [review]

**Comment by priyansh985** [comment]
@Mayureshd-18 and @jvedsaqib

Changes were made successfully now you can review the pull request..

Thank you..

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me! Merging!

**Pull request merged**
