### PR TITLE
Convert categorical variables to numeric variables

### LINKED ISSUE #111: [BUG] Convert categorical variables to numeric variables
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

There are categorical values which need to be to converted into numeric for correct expected output
Screenshot 2024-10-13 104303

### Steps to Reproduce

Include any relevant details like:

- Page stock_market(complete).ipynb
- I was executing the code when it displayed the error of categorical variables
- The date column is categorical which has to be converted into numeric

### Screenshots

_No response_

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this.

I will convert the categorical values into numeric using scikit learn

### PR DESCRIPTION
**Pull request by shristirwt**
Issue Reference: Fixes #111

Description of changes: The categorical variables were converted to numeric ones for plotting

Screenshot 2024-10-14 170805

### CODE REVIEW

**Comment by jvedsaqib** [comment]
> I have tried every way possible to correct the issue but nothing is working

Hey @shristirwt 
Can you please elaborate?

**Comment by shristirwt** [comment]
> > I have tried every way possible to correct the issue but nothing is working
> 
> Hey @shristirwt Can you please elaborate?
> 
> Also edit your 1st comment and add keywords like fixes/closes before the issue number

I have made the changes. 
I am talking about the checks i.e. PR Contribution Rules Check 
I edited the PR many times but it did not fix it

Screenshot 2024-10-14 225929

**Comment by jvedsaqib** [comment]
@shristirwt  It's done! 

The action checks required a specific format. Thanks for pointing out this issue.
I've updated your PR comment, you can check it.

**Review by jvedsaqib — APPROVED** [review]

**Comment by shristirwt** [comment]
> @shristirwt It's done!
> 
> The action checks required a specific format. Thanks for pointing out this issue. I've updated your PR comment, you can check it.

Thank you so much

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Pull request merged**
