### PR TITLE
Github actions for more connectivity!

### LINKED ISSUE #154: Github actions for more connectivity!
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @rohitinu6 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

### PR DESCRIPTION
**Pull request by smog-root**
Closes #154 

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @rohitinu6 

_**Note**_: Add all the labels and assign me to this PR !!

### CODE REVIEW

**Comment by Mayureshd-18** [comment]
@smog-root Why use the word 'chaotic'?

**Comment by Mayureshd-18** [comment]
@smog-root Have you tested this feature on your branch? If not please do that and if already done please attach the screenshots of the same here.

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@smog-root  Have you tested this feature on your branch? If not please do that and if already done please attach the screenshots of the same here.

Thanks & Regards

**Comment by smog-root** [comment]
> @smog-root Why use the word 'chaotic'?

typo

**Comment by smog-root** [comment]
**Proof**:

**Issue open and close:**

Screenshot 2024-10-21 152058
<br>

**PR raise and  merged:**
Screenshot 2024-10-21 160211

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Review by rohitinu6 — APPROVED** [review]

**Comment by smog-root** [comment]
@rohitinu6 merge it!!

**Comment by smog-root** [comment]
@rohitinu6 ??

**Review by Mayureshd-18 — APPROVED** [review]
Merging!

**Review by MastanSayyad — COMMENTED** [review]
as this PR has level 2 and considering that here 3 workflows are added I'll be removing levels from PR #147 

Considering you have done all workflows in single repo which will have level 2

**GUIDELINES:**

image

**Comment by smog-root** [comment]
> as this PR has level 2 and considering that here 3 workflows are added I'll be removing levels from PR #147 
> 
> Considering you have done all workflows in single repo which will have level 2
> 
> **GUIDELINES:**
> 
> image
> 
> 

Okay!!

**Pull request merged**
