### PR TITLE
Created ARIMA model

### LINKED ISSUE #41: Train ARIMA (Autoregressive Integrated Moving Average) for stock predition
Hello @rohitinu6,
I'm Darsh Agrawal, a fellow contributor. I'm interested in working on stock prediction using the ARIMA (Autoregressive Integrated Moving Average) model. ARIMA is a statistical method for time series analysis that can be applied to stock prediction tasks.
If you think this approach aligns with the project goals, I would appreciate being assigned to this task.

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
Fixed issue : #41
------------------------------------ 
Closes #41 
------------------------------------
stages of training arima :

- intially just on Dates and Close prices
- combining with LSTM
- updating data to include days , lags and other features and include while training

Current RMSE : 4.67

i couldnt upload the model and scaler files due to space constraints but by running ARIMA_V2.py , the respective files will be created automatically

Darsh Agrawal GSSoC 24 extd contributor

### CODE REVIEW

**Comment by DarshAgrawal14** [comment]
As this model was not easy , I would appreciate if you would label it as level3

**Comment by DarshAgrawal14** [comment]
@rohitinu6 , please let me know if any further changes are needed. Otherwise, I would appreciate it if you could merge the PR.

**Comment by Mayureshd-18** [comment]
@DarshAgrawal14  Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Thanks & regards.

**Comment by DarshAgrawal14** [comment]
@Mayureshd-18  I added the 'closes' keyword along with issue number , if anything else , let me know.

**Review by Mayureshd-18 — APPROVED** [review]
Looks good to me!

**Comment by DarshAgrawal14** [comment]
@rohitinu6  ,The pull request was submitted 4 days ago and received approval from @Mayureshd-18  day before yesterday. Could you kindly provide an update on the cause of the delay?

**Review by Mayureshd-18 — APPROVED** [review]
Lgtm!

**Review by jvedsaqib — APPROVED** [review]

**Comment by DarshAgrawal14** [comment]
can you add the Labels
gssoc-ext , hacktoberfest-accepted and level label to the PR please.

**Comment by Mayureshd-18** [comment]
Just add the appropriate level label and then I can merge it

**Comment by DarshAgrawal14** [comment]
the label given in the issue is 2 but I asking for level 3  because, doing time series analysis was time consuming .The major part of the project was that i added additional features such as moving averages which i found by learning stock prediction and dividing dates into peices in order to notice the days which is important for both share prices estimation and time series analysis . general time series analysis include taking dataset , creating model with best p , d , q order and other deep learning steps. but the steps i mentioned is what that makes the model better

**Review by Mayureshd-18 — APPROVED** [review]

**Pull request merged**
