### PR TITLE
Added r2_score and performed time series decomposion on data(Issue No:93)

### PR DESCRIPTION
**Pull request by DataWorshipper**
Have added the r2_score metric and performed some time series decomposition on data

### CODE REVIEW

**Comment by DataWorshipper** [comment]
Can someone please help me resolving the merge conflict, I am new to this

**Comment by rohitinu6** [comment]
@DataWorshipper please mention the issue number in your PR using #, followed by your issue number which is assigned to you.

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@DataWorshipper  Please link the issue using keywords. (fixes/closes..) You can find the detailed info about the same here:
https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

If needed, please check out merged PRs for reference.

Thanks & regards

**Review by jvedsaqib — CHANGES_REQUESTED** [review]
@DataWorshipper sync with the latest branch and resolve conflicts

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
@DataWorshipper Please update and resolve the conflicts.

Thanks and regards

**Review by Mayureshd-18 — CHANGES_REQUESTED** [review]
Closing this PR due to long period of inactivity. Please feel free to reopen if needed.
Thanks,
Mayuresh

**Pull request closed without merging**
